name: terraform-destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/module-2

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::685289845863:role/GitHubActionsTerraformModule2
          aws-region: us-east-1

      - run: terraform init -input=false
      - run: terraform destroy -input=false -auto-approve
