name: terraform-apply

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/module-2

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::685289845863:role/GitHubActionsTerraformModule2
          aws-region: us-east-1

      - name: Terraform init (S3 backend)
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan -input=false -no-color

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve
